
def exception(self):
	raise TypeError("hello exception")
